name: "JFrog CLI Example"
on:
  [push]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: "https://psemea.jfrog.io"
  JTOKEN: "cmVmdGtuOjAxOjE3MjgzODk5MzY6bW54YVp6TVBhck04ZUZGb1B1SWljOE5sQzZI"
  # github.repository as <account>/<repo>
jobs:
  npmbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ env.REGISTRY }}
          JF_ACCESS_TOKEN: ${{ env.JTOKEN }}
      - name: Setup NodeJS
        uses: actions/setup-node@v3
      - name: Run JFrog audit
        run: |
          jf npm-config --repo-resolve sr-npm-dev --repo-deploy sr-npm-dev
          jf npm install --build-name $GITHUB_JOB --build-number $GITHUB_RUN_ID --project sr
          # jf audit . --fail=true
          # Collect environment variables for the build
          jf rt bce $GITHUB_JOB $GITHUB_RUN_ID --project sr
          # Collect VCS details from git and add them to the build
          jf rt bag $GITHUB_JOB $GITHUB_RUN_ID --project sr
          # Publish build info
          jf npm publish --build-name $GITHUB_JOB --build-number $GITHUB_RUN_ID --project sr
          jf rt bp $GITHUB_JOB $GITHUB_RUN_ID --project ad
          echo $?
